# Generated by Django 4.2.5 on 2023-10-07 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Onehed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('res', models.BooleanField(default=False)),
            ],
        ),
    ]
